### ISSUE TITLE
The "path" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by cpburnz** [shellscape/webpack-manifest-plugin#256]
- Manifest Plugin Version: 3.1.0
- Webpack Version: 5.26.3
- Operating System (or Browser): Ubuntu 18.04
- Node Version: 14.2.0
- Link to reproduction _(⚠️ read below)_: https://github.com/cpburnz/webpack-manifest-plugin-path-test

### Expected Behavior

Running the following should succeed:

```bash
npx webpack --mode production
```

### Actual Behavior

Running the following fails:

```bash
npx webpack --mode production
```

With the output:

```
[webpack-cli] TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:121:11)
    at resolve (path.js:980:7)
    at WebpackManifestPlugin.apply (/home/.../webpack-manifest-plugin-path-test/node_modules/webpack-manifest-plugin/lib/index.js:36:30)
    at createCompiler (/home/.../webpack-manifest-plugin-path-test/node_modules/webpack/lib/webpack.js:71:12)
    at create (/home/.../webpack-manifest-plugin-path-test/node_modules/webpack/lib/webpack.js:118:16)
    at webpack (/home/.../webpack-manifest-plugin-path-test/node_modules/webpack/lib/webpack.js:126:47)
    at WebpackCLI.f [as webpack] (/home/.../webpack-manifest-plugin-path-test/node_modules/webpack/lib/index.js:41:15)
    at WebpackCLI.createCompiler (/home/.../webpack-manifest-plugin-path-test/node_modules/webpack-cli/lib/webpack-cli.js:1678:29)
    at async WebpackCLI.buildCommand (/home/.../webpack-manifest-plugin-path-test/node_modules/webpack-cli/lib/webpack-cli.js:1785:20)
    at async Command.<anonymous> (/home/.../webpack-manifest-plugin-path-test/node_modules/webpack-cli/lib/webpack-cli.js:564:25) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

### Additional Information

The webpack-manifest-plugin did not previously require `output.path` to be set in Webpack 4. Now in Webpack 5 the manifest plugin fails unless `output.path` is set. Webpack 5's [migration guide](https://webpack.js.org/migrate/5/#clean-up-configuration) recommends omitting `output.path` if it is going to be the default of `path.resolve(__dirname, 'dist')`. By following the recommendations by Webpack 5 the manifest plugin does not work by default. The manifest plugin's README makes no mention of now requiring `output.path` to be set.

**Comment by ayanonly1** [comment]
+1 
I am also facing the same error issue.

**Comment by shellscape** [comment]
@ayanonly1 Please do not post "me too" replies. They help no one and create noise. Use the reaction buttons instead.

**Comment by cpburnz** [comment]
This regression is still present as of the latest version 5.38.1.

**Comment by shellscape** [comment]
@cpburnz please feel free to step up and contribute a PR to resolve it. the stale bot is there to address issues which haven't received any support. If after 60 days without activity an issue doesn't get any support from the community, and I haven't had time to address it, it's unlikely to be resolved. Please petition/rally the community or consider contributing a fix.

**Comment by xavianaxw** [comment]
I had this issue and it was just missing the setting `output.path` on the webpack config itself.

```
output: {
  path: path.resolve(__dirname, config.paths.dist.base),
  //... everything else
}
```

Not sure if it's the same issue you're running into @cpburnz
